"""Controller-independent bounded movement-authority evaluation."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, replace
from datetime import timedelta
from enum import StrEnum
from threading import RLock
from typing import Literal, NewType, TypeAlias

from gleiswerk.evidence_validation import (
    EvidenceRejection,
    EvidenceRejectionKind,
    EvidenceValidationResult,
)
from gleiswerk.route_reservations import (
    Reservation,
    ReservationId,
    ReservationInspection,
    ReservationOwner,
)
from gleiswerk.topology import ClaimResource, RouteDefinitionId

MovementAuthorityId = NewType("MovementAuthorityId", str)
"""An opaque identifier generated by a movement-authority evaluator."""


class MovementAuthorityFailureKind(StrEnum):
    """The ordered categories that can deny or revoke an authority."""

    RESERVATION = "reservation"
    SCOPE = "scope"
    TOPOLOGY_REVISION = "topology-revision"
    OCCUPANCY_EVIDENCE = "occupancy-evidence"
    DEVICE_POSITION_EVIDENCE = "device-position-evidence"
    EXPIRATION = "expiration"


@dataclass(frozen=True, slots=True)
class MovementAuthorityFailure:
    """One stable, minimal explanation for a denied or revoked authority."""

    kind: MovementAuthorityFailureKind
    target: str
    evidence_rejection: EvidenceRejection | None = None


@dataclass(frozen=True, slots=True)
class MovementAuthorityScope:
    """The complete reservation claims asserted by one authority."""

    claims: tuple[ClaimResource, ...]

    def __post_init__(self) -> None:
        object.__setattr__(self, "claims", tuple(sorted(self.claims, key=_claim_key)))


@dataclass(frozen=True, slots=True)
class MovementAuthorityRequest:
    """Request a finite authority over one live reservation."""

    owner: ReservationOwner
    reservation_id: ReservationId
    evidence: EvidenceValidationResult
    valid_for: timedelta

    def __post_init__(self) -> None:
        if self.valid_for <= timedelta():
            raise ValueError("movement authority validity must be positive")


@dataclass(frozen=True, slots=True)
class MovementAuthority:
    """An immutable, bounded authority with an irreversible terminal state."""

    id: MovementAuthorityId
    reservation_id: ReservationId
    owner: ReservationOwner
    route_id: RouteDefinitionId
    topology_revision: str
    scope: MovementAuthorityScope
    issued_at: float
    expires_at: float
    status: Literal["live", "revoked"] = "live"
    revocation: MovementAuthorityFailure | None = None

    @property
    def is_live(self) -> bool:
        """Whether this record has not reached a terminal state."""

        return self.status == "live"


@dataclass(frozen=True, slots=True)
class EvaluateMovementAuthorityResult:
    """The complete outcome of one atomic issuance decision."""

    outcome: Literal["granted", "denied"]
    authority: MovementAuthority | None = None
    denial_reason: MovementAuthorityFailure | None = None


@dataclass(frozen=True, slots=True)
class AuthorityNotFound:
    """No authority record has the supplied opaque ID."""

    kind: Literal["not-found"] = "not-found"


ReevaluationDenialReason: TypeAlias = AuthorityNotFound


@dataclass(frozen=True, slots=True)
class ReevaluateMovementAuthorityResult:
    """The current state after checking one authority's dependencies."""

    outcome: Literal["live", "revoked", "not-found"]
    authority: MovementAuthority | None = None
    denial_reason: ReevaluationDenialReason | None = None


@dataclass(frozen=True, slots=True)
class MovementAuthorityInspection:
    """A deterministic read-only snapshot of issued authority records."""

    authorities: tuple[MovementAuthority, ...]

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "authorities",
            tuple(sorted(self.authorities, key=lambda item: item.id)),
        )


class MovementAuthorityEvaluator:
    """Issue and reevaluate authorities over immutable core snapshots.

    The evaluator owns only authority records.  It never changes reservation
    state, commands equipment, or reads a wall clock.  Callers supply a current
    reservation inspection and evidence-validation result for every decision.
    """

    def __init__(
        self,
        topology_revision: str,
        maximum_validity: timedelta,
        monotonic_clock: Callable[[], float],
    ) -> None:
        if not topology_revision:
            raise ValueError("topology revision must be nonempty")
        if maximum_validity <= timedelta():
            raise ValueError("movement authority maximum validity must be positive")
        self._topology_revision = topology_revision
        self._maximum_validity = maximum_validity
        self._monotonic_clock = monotonic_clock
        self._authorities: dict[MovementAuthorityId, MovementAuthority] = {}
        self._next_authority_number = 1
        self._lock = RLock()

    def evaluate(
        self, request: MovementAuthorityRequest, reservations: ReservationInspection
    ) -> EvaluateMovementAuthorityResult:
        """Grant one authority only when every ordered prerequisite holds."""

        with self._lock:
            issued_at = self._monotonic_clock()
            failure = self._failure_for(request, reservations, issued_at)
            if failure is not None:
                return EvaluateMovementAuthorityResult("denied", denial_reason=failure)

            reservation = _live_reservation(reservations, request.reservation_id)
            assert reservation is not None
            authority = MovementAuthority(
                MovementAuthorityId(f"authority-{self._next_authority_number}"),
                reservation.id,
                reservation.owner,
                reservation.route_id,
                reservation.topology_revision,
                MovementAuthorityScope(reservation.claims),
                issued_at,
                issued_at + request.valid_for.total_seconds(),
            )
            self._next_authority_number += 1
            self._authorities[authority.id] = authority
            return EvaluateMovementAuthorityResult("granted", authority=authority)

    def reevaluate(
        self,
        authority_id: MovementAuthorityId,
        reservations: ReservationInspection,
        evidence: EvidenceValidationResult,
    ) -> ReevaluateMovementAuthorityResult:
        """Revoke a live authority when a current dependency no longer holds."""

        with self._lock:
            authority = self._authorities.get(authority_id)
            if authority is None:
                return ReevaluateMovementAuthorityResult(
                    "not-found", denial_reason=AuthorityNotFound()
                )
            if not authority.is_live:
                return ReevaluateMovementAuthorityResult("revoked", authority=authority)

            request = MovementAuthorityRequest(
                authority.owner,
                authority.reservation_id,
                evidence,
                self._maximum_validity,
            )
            failure = self._failure_for(
                request, reservations, self._monotonic_clock(), authority.expires_at
            )
            if failure is not None:
                authority = replace(authority, status="revoked", revocation=failure)
                self._authorities[authority.id] = authority
                return ReevaluateMovementAuthorityResult("revoked", authority=authority)
            return ReevaluateMovementAuthorityResult("live", authority=authority)

    def inspect(self) -> MovementAuthorityInspection:
        """Return every authority, including terminal records, in stable order."""

        with self._lock:
            return MovementAuthorityInspection(tuple(self._authorities.values()))

    def _failure_for(
        self,
        request: MovementAuthorityRequest,
        reservations: ReservationInspection,
        now: float,
        expires_at: float | None = None,
    ) -> MovementAuthorityFailure | None:
        reservation = _live_reservation(reservations, request.reservation_id)
        if reservation is None or reservation.owner != request.owner:
            return MovementAuthorityFailure(
                MovementAuthorityFailureKind.RESERVATION, str(request.reservation_id)
            )
        if request.evidence.plan_route_id != reservation.route_id:
            return MovementAuthorityFailure(
                MovementAuthorityFailureKind.SCOPE, str(reservation.route_id)
            )
        revisions = (
            self._topology_revision,
            reservations.topology_revision,
            reservation.topology_revision,
            request.evidence.topology_revision,
            request.evidence.plan_topology_revision,
        )
        if len(set(revisions)) != 1:
            return MovementAuthorityFailure(
                MovementAuthorityFailureKind.TOPOLOGY_REVISION,
                self._topology_revision,
            )
        evidence_failure = _evidence_failure(request.evidence)
        if evidence_failure is not None:
            return evidence_failure
        deadline = (
            expires_at
            if expires_at is not None
            else now + request.valid_for.total_seconds()
        )
        if request.valid_for > self._maximum_validity or deadline <= now:
            return MovementAuthorityFailure(
                MovementAuthorityFailureKind.EXPIRATION, str(request.reservation_id)
            )
        return None


def _live_reservation(
    inspection: ReservationInspection, reservation_id: ReservationId
) -> Reservation | None:
    return next(
        (item for item in inspection.reservations if item.id == reservation_id), None
    )


def _evidence_failure(
    evidence: EvidenceValidationResult,
) -> MovementAuthorityFailure | None:
    occupancy_kinds = {
        EvidenceRejectionKind.UNKNOWN_OCCUPANCY_ZONE,
        EvidenceRejectionKind.DUPLICATE_OCCUPANCY_EVIDENCE,
        EvidenceRejectionKind.MISSING_OCCUPANCY_COVERAGE,
        EvidenceRejectionKind.AMBIGUOUS_OCCUPANCY_COVERAGE,
        EvidenceRejectionKind.MISSING_OCCUPANCY_EVIDENCE,
        EvidenceRejectionKind.OCCUPIED,
    }
    device_kinds = {
        EvidenceRejectionKind.UNKNOWN_CONTROL_DEVICE,
        EvidenceRejectionKind.DUPLICATE_DEVICE_EVIDENCE,
        EvidenceRejectionKind.MISSING_DEVICE_EVIDENCE,
        EvidenceRejectionKind.UNALIGNED,
    }
    occupancy_targets = {str(item.zone_id) for item in evidence.occupancy_results}
    device_targets = {str(item.device_id) for item in evidence.device_position_results}
    occupancy = [
        item
        for item in evidence.rejections
        if item.kind in occupancy_kinds
        or (
            item.target in occupancy_targets
            and item.kind is not EvidenceRejectionKind.REVISION_MISMATCH
        )
    ]
    device = [
        item
        for item in evidence.rejections
        if item.kind in device_kinds
        or (
            item.target in device_targets
            and item.kind is not EvidenceRejectionKind.REVISION_MISMATCH
        )
    ]
    if occupancy:
        rejection = min(
            occupancy, key=lambda item: (item.target, item.kind, item.source_ids)
        )
        return MovementAuthorityFailure(
            MovementAuthorityFailureKind.OCCUPANCY_EVIDENCE,
            rejection.target,
            rejection,
        )
    if device:
        rejection = min(
            device, key=lambda item: (item.target, item.kind, item.source_ids)
        )
        return MovementAuthorityFailure(
            MovementAuthorityFailureKind.DEVICE_POSITION_EVIDENCE,
            rejection.target,
            rejection,
        )
    if evidence.rejections:
        rejection = min(
            evidence.rejections,
            key=lambda item: (item.target, item.kind, item.source_ids),
        )
        return MovementAuthorityFailure(
            MovementAuthorityFailureKind.TOPOLOGY_REVISION,
            rejection.target,
            rejection,
        )
    return None


def _claim_key(claim: ClaimResource) -> tuple[str, str]:
    return (claim.__class__.__name__, str(claim.id))
