"""Immutable, controller-independent contracts for RoutePlan reservations.

This module deliberately contains no reservation state or locking behavior.
``ReservationManager`` and its atomic operations are specified by the next
implementation increment; these values are its public input and result shape.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Literal, NewType, TypeAlias

from gleiswerk.topology import (
    ClaimResource,
    ControlDeviceId,
    DevicePositionId,
    DeviceRequirement,
    JunctionResource,
    RouteDefinitionId,
    RoutePlan,
    TrackSectionResource,
)

ReservationId = NewType("ReservationId", str)
"""An opaque identifier generated by a reservation manager on acquisition."""

ReservationOwner = NewType("ReservationOwner", str)
"""An opaque, stable identity supplied by the embedding application."""


@dataclass(frozen=True, slots=True)
class AcquireReservationRequest:
    """Request one new reservation for a validated RoutePlan."""

    owner: ReservationOwner
    plan: RoutePlan


@dataclass(frozen=True, slots=True)
class ReleaseReservationRequest:
    """Request release of one opaque reservation owned by the caller."""

    owner: ReservationOwner
    reservation_id: ReservationId


@dataclass(frozen=True, slots=True)
class Reservation:
    """An immutable record of the claims and constraints held at runtime."""

    id: ReservationId
    owner: ReservationOwner
    route_id: RouteDefinitionId
    topology_revision: str
    claims: tuple[ClaimResource, ...]
    requirements: tuple[DeviceRequirement, ...]
    claim_provenance: Mapping[ClaimResource, tuple[str, ...]]
    requirement_provenance: Mapping[ControlDeviceId, tuple[str, ...]]

    def __post_init__(self) -> None:
        object.__setattr__(self, "claims", tuple(sorted(self.claims, key=_claim_key)))
        object.__setattr__(
            self,
            "requirements",
            tuple(
                sorted(self.requirements, key=lambda requirement: requirement.device_id)
            ),
        )
        object.__setattr__(
            self,
            "claim_provenance",
            MappingProxyType(
                {
                    resource: tuple(sources)
                    for resource, sources in sorted(
                        self.claim_provenance.items(),
                        key=lambda item: _claim_key(item[0]),
                    )
                }
            ),
        )
        object.__setattr__(
            self,
            "requirement_provenance",
            MappingProxyType(
                {
                    device_id: tuple(sources)
                    for device_id, sources in sorted(
                        self.requirement_provenance.items()
                    )
                }
            ),
        )


@dataclass(frozen=True, slots=True)
class OverlappingReservationClaim:
    """One requested exclusive claim already held by one reservation."""

    resource: ClaimResource
    requested_provenance: tuple[str, ...]
    held_reservation_id: ReservationId
    held_provenance: tuple[str, ...]

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "requested_provenance", tuple(self.requested_provenance)
        )
        object.__setattr__(self, "held_provenance", tuple(self.held_provenance))


@dataclass(frozen=True, slots=True)
class IncompatibleReservationDeviceConstraint:
    """One requested Control Device value that conflicts with a held value."""

    control_device: ControlDeviceId
    requested_position: DevicePositionId
    requested_provenance: tuple[str, ...]
    held_reservation_id: ReservationId
    held_position: DevicePositionId
    held_provenance: tuple[str, ...]

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "requested_provenance", tuple(self.requested_provenance)
        )
        object.__setattr__(self, "held_provenance", tuple(self.held_provenance))


@dataclass(frozen=True, slots=True)
class NoActiveTopology:
    """The manager cannot accept plans until a topology revision is active."""

    kind: Literal["no-active-topology"] = "no-active-topology"


@dataclass(frozen=True, slots=True)
class InvalidReservationPlan:
    """The supplied plan failed the manager's defensive plan validation."""

    kind: Literal["invalid-plan"] = "invalid-plan"


@dataclass(frozen=True, slots=True)
class TopologyRevisionMismatch:
    """The plan revision differs from the manager's active revision."""

    active_topology_revision: str
    plan_topology_revision: str
    kind: Literal["revision-mismatch"] = "revision-mismatch"


@dataclass(frozen=True, slots=True)
class IncompatibleReservation:
    """All deterministic conflicts that prevent one atomic acquisition."""

    claim_conflicts: tuple[OverlappingReservationClaim, ...]
    device_constraint_conflicts: tuple[IncompatibleReservationDeviceConstraint, ...]
    kind: Literal["incompatible"] = "incompatible"

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "claim_conflicts",
            tuple(
                sorted(
                    self.claim_conflicts,
                    key=lambda conflict: (
                        *_claim_key(conflict.resource),
                        conflict.held_reservation_id,
                    ),
                )
            ),
        )
        object.__setattr__(
            self,
            "device_constraint_conflicts",
            tuple(
                sorted(
                    self.device_constraint_conflicts,
                    key=lambda conflict: (
                        conflict.control_device,
                        conflict.held_reservation_id,
                    ),
                )
            ),
        )


AcquireDenialReason: TypeAlias = (
    NoActiveTopology
    | InvalidReservationPlan
    | TopologyRevisionMismatch
    | IncompatibleReservation
)


@dataclass(frozen=True, slots=True)
class AcquireReservationResult:
    """The complete outcome of one acquire request, with no implicit state change."""

    outcome: Literal[
        "acquired",
        "invalid-plan",
        "revision-mismatch",
        "incompatible",
        "no-active-topology",
    ]
    reservation: Reservation | None = None
    denial_reason: AcquireDenialReason | None = None


@dataclass(frozen=True, slots=True)
class ReservationNotFound:
    """No live reservation has the requested opaque ID."""

    kind: Literal["not-found"] = "not-found"


@dataclass(frozen=True, slots=True)
class ReservationNotOwner:
    """A different owner holds the reservation; no record details are exposed."""

    kind: Literal["not-owner"] = "not-owner"


ReleaseDenialReason: TypeAlias = ReservationNotFound | ReservationNotOwner


@dataclass(frozen=True, slots=True)
class ReleaseReservationResult:
    """The complete outcome of one whole-reservation release request."""

    outcome: Literal["released", "not-found", "not-owner"]
    reservation_id: ReservationId | None = None
    denial_reason: ReleaseDenialReason | None = None


@dataclass(frozen=True, slots=True)
class ReservationInspection:
    """A read-only deterministic snapshot of one manager's held reservations."""

    active_topology_revision: str | None
    reservations: tuple[Reservation, ...]

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "reservations",
            tuple(sorted(self.reservations, key=lambda reservation: reservation.id)),
        )


def _claim_key(claim: ClaimResource) -> tuple[str, str]:
    if isinstance(claim, TrackSectionResource):
        return ("track-section", claim.id)
    if isinstance(claim, JunctionResource):
        return ("junction", claim.id)
    return ("protection-zone", claim.id)
