"""Immutable, controller-independent contracts for RoutePlan reservations.

This module deliberately contains no reservation state or locking behavior.
``ReservationManager`` and its atomic operations are specified by the next
implementation increment; these values are its public input and result shape.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from threading import RLock
from types import MappingProxyType
from typing import Literal, NewType, TypeAlias

from gleiswerk.topology import (
    ClaimResource,
    ControlDeviceId,
    DevicePositionId,
    DeviceRequirement,
    JunctionResource,
    RouteDefinitionId,
    RoutePlan,
    TrackSectionResource,
)

ReservationId = NewType("ReservationId", str)
"""An opaque identifier generated by a reservation manager on acquisition."""

ReservationOwner = NewType("ReservationOwner", str)
"""An opaque, stable identity supplied by the embedding application."""


@dataclass(frozen=True, slots=True)
class AcquireReservationRequest:
    """Request one new reservation for a validated RoutePlan."""

    owner: ReservationOwner
    plan: RoutePlan


@dataclass(frozen=True, slots=True)
class ReleaseReservationRequest:
    """Request release of one opaque reservation owned by the caller."""

    owner: ReservationOwner
    reservation_id: ReservationId


@dataclass(frozen=True, slots=True)
class Reservation:
    """An immutable record of the claims and constraints held at runtime."""

    id: ReservationId
    owner: ReservationOwner
    route_id: RouteDefinitionId
    topology_revision: str
    claims: tuple[ClaimResource, ...]
    requirements: tuple[DeviceRequirement, ...]
    claim_provenance: Mapping[ClaimResource, tuple[str, ...]]
    requirement_provenance: Mapping[ControlDeviceId, tuple[str, ...]]

    def __post_init__(self) -> None:
        object.__setattr__(self, "claims", tuple(sorted(self.claims, key=_claim_key)))
        object.__setattr__(
            self,
            "requirements",
            tuple(
                sorted(self.requirements, key=lambda requirement: requirement.device_id)
            ),
        )
        object.__setattr__(
            self,
            "claim_provenance",
            MappingProxyType(
                {
                    resource: tuple(sources)
                    for resource, sources in sorted(
                        self.claim_provenance.items(),
                        key=lambda item: _claim_key(item[0]),
                    )
                }
            ),
        )
        object.__setattr__(
            self,
            "requirement_provenance",
            MappingProxyType(
                {
                    device_id: tuple(sources)
                    for device_id, sources in sorted(
                        self.requirement_provenance.items()
                    )
                }
            ),
        )


@dataclass(frozen=True, slots=True)
class OverlappingReservationClaim:
    """One requested exclusive claim already held by one reservation."""

    resource: ClaimResource
    requested_provenance: tuple[str, ...]
    held_reservation_id: ReservationId
    held_provenance: tuple[str, ...]

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "requested_provenance", tuple(self.requested_provenance)
        )
        object.__setattr__(self, "held_provenance", tuple(self.held_provenance))


@dataclass(frozen=True, slots=True)
class IncompatibleReservationDeviceConstraint:
    """One requested Control Device value that conflicts with a held value."""

    control_device: ControlDeviceId
    requested_position: DevicePositionId
    requested_provenance: tuple[str, ...]
    held_reservation_id: ReservationId
    held_position: DevicePositionId
    held_provenance: tuple[str, ...]

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "requested_provenance", tuple(self.requested_provenance)
        )
        object.__setattr__(self, "held_provenance", tuple(self.held_provenance))


@dataclass(frozen=True, slots=True)
class NoActiveTopology:
    """The manager cannot accept plans until a topology revision is active."""

    kind: Literal["no-active-topology"] = "no-active-topology"


@dataclass(frozen=True, slots=True)
class InvalidReservationPlan:
    """The supplied plan failed the manager's defensive plan validation."""

    kind: Literal["invalid-plan"] = "invalid-plan"


@dataclass(frozen=True, slots=True)
class TopologyRevisionMismatch:
    """The plan revision differs from the manager's active revision."""

    active_topology_revision: str
    plan_topology_revision: str
    kind: Literal["revision-mismatch"] = "revision-mismatch"


@dataclass(frozen=True, slots=True)
class IncompatibleReservation:
    """All deterministic conflicts that prevent one atomic acquisition."""

    claim_conflicts: tuple[OverlappingReservationClaim, ...]
    device_constraint_conflicts: tuple[IncompatibleReservationDeviceConstraint, ...]
    kind: Literal["incompatible"] = "incompatible"

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "claim_conflicts",
            tuple(
                sorted(
                    self.claim_conflicts,
                    key=lambda conflict: (
                        *_claim_key(conflict.resource),
                        conflict.held_reservation_id,
                    ),
                )
            ),
        )
        object.__setattr__(
            self,
            "device_constraint_conflicts",
            tuple(
                sorted(
                    self.device_constraint_conflicts,
                    key=lambda conflict: (
                        conflict.control_device,
                        conflict.held_reservation_id,
                    ),
                )
            ),
        )


AcquireDenialReason: TypeAlias = (
    NoActiveTopology
    | InvalidReservationPlan
    | TopologyRevisionMismatch
    | IncompatibleReservation
)


@dataclass(frozen=True, slots=True)
class AcquireReservationResult:
    """The complete outcome of one acquire request, with no implicit state change."""

    outcome: Literal[
        "acquired",
        "invalid-plan",
        "revision-mismatch",
        "incompatible",
        "no-active-topology",
    ]
    reservation: Reservation | None = None
    denial_reason: AcquireDenialReason | None = None


@dataclass(frozen=True, slots=True)
class ReservationNotFound:
    """No live reservation has the requested opaque ID."""

    kind: Literal["not-found"] = "not-found"


@dataclass(frozen=True, slots=True)
class ReservationNotOwner:
    """A different owner holds the reservation; no record details are exposed."""

    kind: Literal["not-owner"] = "not-owner"


ReleaseDenialReason: TypeAlias = ReservationNotFound | ReservationNotOwner


@dataclass(frozen=True, slots=True)
class ReleaseReservationResult:
    """The complete outcome of one whole-reservation release request."""

    outcome: Literal["released", "not-found", "not-owner"]
    reservation_id: ReservationId | None = None
    denial_reason: ReleaseDenialReason | None = None


@dataclass(frozen=True, slots=True)
class ReservationInspection:
    """A read-only deterministic snapshot of one manager's held reservations."""

    active_topology_revision: str | None
    reservations: tuple[Reservation, ...]

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "reservations",
            tuple(sorted(self.reservations, key=lambda reservation: reservation.id)),
        )


class ReservationManager:
    """Atomically hold RoutePlan claims for one active topology revision.

    This manager is intentionally an in-memory, controller-independent core
    component. Acquiring a reservation neither commands a device nor permits a
    train to move.
    """

    def __init__(self, active_topology_revision: str | None = None) -> None:
        self._active_topology_revision = active_topology_revision
        self._reservations: dict[ReservationId, Reservation] = {}
        self._next_reservation_number = 1
        self._lock = RLock()

    def acquire(self, request: AcquireReservationRequest) -> AcquireReservationResult:
        """Atomically acquire every claim in a plan or leave state unchanged."""

        with self._lock:
            if self._active_topology_revision is None:
                return AcquireReservationResult(
                    "no-active-topology", denial_reason=NoActiveTopology()
                )
            if not _is_valid_plan(request.plan):
                return AcquireReservationResult(
                    "invalid-plan", denial_reason=InvalidReservationPlan()
                )
            if request.plan.topology_revision != self._active_topology_revision:
                return AcquireReservationResult(
                    "revision-mismatch",
                    denial_reason=TopologyRevisionMismatch(
                        self._active_topology_revision, request.plan.topology_revision
                    ),
                )

            denial = self._incompatibility_for(request.plan)
            if denial is not None:
                return AcquireReservationResult("incompatible", denial_reason=denial)

            reservation = _reservation_from_plan(
                ReservationId(f"reservation-{self._next_reservation_number}"),
                request.owner,
                request.plan,
            )
            self._next_reservation_number += 1
            self._reservations[reservation.id] = reservation
            return AcquireReservationResult("acquired", reservation=reservation)

    def release(self, request: ReleaseReservationRequest) -> ReleaseReservationResult:
        """Atomically release one whole reservation if it belongs to the owner."""

        with self._lock:
            reservation = self._reservations.get(request.reservation_id)
            if reservation is None:
                return ReleaseReservationResult(
                    "not-found", denial_reason=ReservationNotFound()
                )
            if reservation.owner != request.owner:
                return ReleaseReservationResult(
                    "not-owner", denial_reason=ReservationNotOwner()
                )
            del self._reservations[request.reservation_id]
            return ReleaseReservationResult(
                "released", reservation_id=request.reservation_id
            )

    def inspect(self) -> ReservationInspection:
        """Return an immutable snapshot of the active revision and held records."""

        with self._lock:
            return ReservationInspection(
                self._active_topology_revision, tuple(self._reservations.values())
            )

    def activate_topology(self, topology_revision: str | None) -> bool:
        """Activate a revision only when no reservation is live.

        ``False`` means the current active revision and all held claims were
        preserved. ``None`` deactivates the manager once it is empty.
        """

        with self._lock:
            if self._reservations:
                return False
            self._active_topology_revision = topology_revision
            return True

    def _incompatibility_for(self, plan: RoutePlan) -> IncompatibleReservation | None:
        claim_conflicts: list[OverlappingReservationClaim] = []
        device_conflicts: list[IncompatibleReservationDeviceConstraint] = []
        requested_requirements = {
            requirement.device_id: requirement for requirement in plan.requirements
        }
        for held in self._reservations.values():
            held_claims = set(held.claims)
            for resource in plan.claims:
                if resource in held_claims:
                    claim_conflicts.append(
                        OverlappingReservationClaim(
                            resource,
                            tuple(
                                item.source for item in plan.claim_provenance[resource]
                            ),
                            held.id,
                            held.claim_provenance[resource],
                        )
                    )
            held_requirements = {
                requirement.device_id: requirement for requirement in held.requirements
            }
            for device_id, requested in requested_requirements.items():
                held_requirement = held_requirements.get(device_id)
                if (
                    held_requirement is not None
                    and held_requirement.position_id != requested.position_id
                ):
                    device_conflicts.append(
                        IncompatibleReservationDeviceConstraint(
                            device_id,
                            requested.position_id,
                            tuple(
                                item.source
                                for item in plan.requirement_provenance[device_id]
                            ),
                            held.id,
                            held_requirement.position_id,
                            held.requirement_provenance[device_id],
                        )
                    )
        if not claim_conflicts and not device_conflicts:
            return None
        return IncompatibleReservation(tuple(claim_conflicts), tuple(device_conflicts))


def _claim_key(claim: ClaimResource) -> tuple[str, str]:
    if isinstance(claim, TrackSectionResource):
        return ("track-section", claim.id)
    if isinstance(claim, JunctionResource):
        return ("junction", claim.id)
    return ("protection-zone", claim.id)


def _reservation_from_plan(
    reservation_id: ReservationId, owner: ReservationOwner, plan: RoutePlan
) -> Reservation:
    return Reservation(
        reservation_id,
        owner,
        plan.route_id,
        plan.topology_revision,
        plan.claims,
        plan.requirements,
        {
            resource: tuple(item.source for item in sources)
            for resource, sources in plan.claim_provenance.items()
        },
        {
            device_id: tuple(item.source for item in sources)
            for device_id, sources in plan.requirement_provenance.items()
        },
    )


def _is_valid_plan(plan: RoutePlan) -> bool:
    """Defensively confirm the compiled-plan invariants the manager relies on."""

    if not plan.topology_revision:
        return False
    if len(plan.claims) != len(set(plan.claims)):
        return False
    if len(plan.requirements) != len(
        {requirement.device_id for requirement in plan.requirements}
    ):
        return False
    if set(plan.claim_provenance) != set(plan.claims):
        return False
    if set(plan.requirement_provenance) != {
        requirement.device_id for requirement in plan.requirements
    }:
        return False
    return all(plan.claim_provenance[claim] for claim in plan.claims) and all(
        plan.requirement_provenance[requirement.device_id]
        for requirement in plan.requirements
    )
